// design/pages/blog.vue
<template>
    <div class="min-h-screen bg-gray-50">
      <!-- Hero Section -->
      <section class="bg-white py-16 border-b border-gray-200">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="text-center">
            <h1 class="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
              Developer Blog
            </h1>
            <p class="text-xl text-gray-600 max-w-3xl mx-auto">
              Insights, tutorials, and the latest trends in web development from our community of experts.
            </p>
          </div>
        </div>
      </section>
  
      <!-- Blog Content -->
      <section class="py-16">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <!-- Filters -->
          <div class="flex flex-wrap gap-4 mb-12">
            <button 
              v-for="category in categories" 
              :key="category"
              class="px-4 py-2 rounded-full border border-gray-300 hover:border-primary-500 hover:text-primary-600 transition-colors"
              :class="selectedCategory === category ? 'bg-primary-600 text-white border-primary-600' : ''"
              @click="selectedCategory = category"
            >
              {{ category }}
            </button>
          </div>
  
          <!-- Blog Posts Grid -->
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <article 
              v-for="post in filteredPosts" 
              :key="post.id"
              class="card overflow-hidden"
            >
              <img 
                :src="post.image" 
                :alt="post.title"
                class="w-full h-48 object-cover"
              >
              <div class="p-6">
                <div class="flex items-center text-sm text-gray-500 mb-3">
                  <span class="bg-primary-100 text-primary-800 px-2 py-1 rounded-full text-xs font-medium mr-3">
                    {{ post.category }}
                  </span>
                  <span>{{ post.date }}</span>
                </div>
                <h2 class="text-xl font-bold text-gray-900 mb-3 hover:text-primary-600 transition-colors">
                  {{ post.title }}
                </h2>
                <p class="text-gray-600 mb-4">{{ post.excerpt }}</p>
                <div class="flex items-center justify-between">
                  <div class="flex items-center">
                    <img 
                      :src="post.author.avatar" 
                      :alt="post.author.name"
                      class="w-8 h-8 rounded-full mr-3"
                    >
                    <span class="text-sm text-gray-700">{{ post.author.name }}</span>
                  </div>
                  <button class="text-primary-600 hover:text-primary-700 font-medium">
                    Read More
                  </button>
                </div>
              </div>
            </article>
          </div>
        </div>
      </section>
    </div>
  </template>
  
  <script setup>
  useHead({
    title: 'Blog - WebDevLab',
    meta: [
      { name: 'description', content: 'Read the latest web development tutorials, insights, and industry trends.' }
    ]
  })
  
  const selectedCategory = ref('All')
  const categories = ['All', 'JavaScript', 'React', 'Vue.js', 'Node.js', 'CSS', 'Career Tips']
  
  const posts = [
    {
      id: 1,
      title: 'Building Modern Web Applications with Vue 3',
      excerpt: 'Learn how to leverage the latest features in Vue 3 to build performant web applications.',
      category: 'Vue.js',
      date: 'Jan 15, 2025',
      image: 'https://images.pexels.com/photos/270348/pexels-photo-270348.jpeg',
      author: {
        name: 'Sarah Johnson',
        avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?w=100&h=100&fit=crop&crop=face'
      }
    },
    {
      id: 2,
      title: 'JavaScript ES2024: New Features You Should Know',
      excerpt: 'Discover the latest JavaScript features and how they can improve your development workflow.',
      category: 'JavaScript',
      date: 'Jan 12, 2025',
      image: 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg',
      author: {
        name: 'Mike Chen',
        avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?w=100&h=100&fit=crop&crop=face'
      }
    },
    {
      id: 3,
      title: 'Career Growth: From Junior to Senior Developer',
      excerpt: 'Essential tips and strategies for advancing your career in software development.',
      category: 'Career Tips',
      date: 'Jan 10, 2025',
      image: 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg',
      author: {
        name: 'Alex Rivera',
        avatar: 'https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?w=100&h=100&fit=crop&crop=face'
      }
    }
  ]
  
  const filteredPosts = computed(() => {
    if (selectedCategory.value === 'All') {
      return posts
    }
    return posts.filter(post => post.category === selectedCategory.value)
  })
  </script>

// design/pages/Blog.tsx
import { Calendar, Clock, User } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const blogPosts = [
  {
    id: 1,
    title: "The Future of Online Learning",
    excerpt: "Exploring how technology is reshaping education and creating new opportunities for learners worldwide.",
    author: "Sarah Johnson",
    date: "2024-01-15",
    readTime: "5 min read",
    category: "Education",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=250&fit=crop"
  },
  {
    id: 2,
    title: "Career Tips for Tech Professionals",
    excerpt: "Essential strategies for advancing your career in the rapidly evolving technology industry.",
    author: "Mike Chen",
    date: "2024-01-12",
    readTime: "7 min read",
    category: "Career",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=400&h=250&fit=crop"
  },
  {
    id: 3,
    title: "Building a Learning Community",
    excerpt: "How forums and discussions enhance the learning experience and create lasting connections.",
    author: "Emma Davis",
    date: "2024-01-10",
    readTime: "4 min read",
    category: "Community",
    image: "https://images.unsplash.com/photo-1543269664-56d93c1b41a6?w=400&h=250&fit=crop"
  },
];

export default function Blog() {
  return (
    <div className="copy-protection">
      <div className="bg-gradient-hero text-white py-16">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-2xl text-center">
            <h1 className="text-4xl font-bold tracking-tight sm:text-6xl">
              Blog & Articles
            </h1>
            <p className="mt-6 text-lg leading-8 text-primary-foreground/80">
              Insights, tips, and stories from the world of education and technology
            </p>
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-7xl px-6 py-16 lg:px-8">
        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          {blogPosts.map((post) => (
            <Card key={post.id} className="card-hover overflow-hidden">
              <div className="aspect-video overflow-hidden">
                <img
                  src={post.image}
                  alt={post.title}
                  className="h-full w-full object-cover transition-smooth hover:scale-105"
                />
              </div>
              <CardHeader>
                <div className="flex items-center justify-between mb-2">
                  <Badge variant="secondary">{post.category}</Badge>
                  <div className="flex items-center text-sm text-muted-foreground">
                    <Clock className="h-4 w-4 mr-1" />
                    {post.readTime}
                  </div>
                </div>
                <CardTitle className="text-xl hover:text-primary transition-smooth cursor-pointer">
                  {post.title}
                </CardTitle>
                <CardDescription>{post.excerpt}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between text-sm text-muted-foreground">
                  <div className="flex items-center">
                    <User className="h-4 w-4 mr-1" />
                    {post.author}
                  </div>
                  <div className="flex items-center">
                    <Calendar className="h-4 w-4 mr-1" />
                    {new Date(post.date).toLocaleDateString()}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
}
